# Generated by Django 3.2.9 on 2021-11-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211115_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
