# Generated by Django 3.2.9 on 2021-11-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211124_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
