# Generated by Django 3.2.9 on 2021-11-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211125_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
